"""empty message

Revision ID: 5e1378a49828
Revises: f93fc32da02c
Create Date: 2022-09-24 16:11:29.694244

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5e1378a49828'
down_revision = 'f93fc32da02c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('favorites', 'characters_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('favorites', 'location_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.add_column('location', sa.Column('type_', sa.String(length=120), nullable=False))
    op.drop_index('type', table_name='location')
    op.drop_index('type_2', table_name='location')
    op.create_unique_constraint(None, 'location', ['type_'])
    op.drop_column('location', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('type', mysql.VARCHAR(length=120), nullable=False))
    op.drop_constraint(None, 'location', type_='unique')
    op.create_index('type_2', 'location', ['type'], unique=False)
    op.create_index('type', 'location', ['type'], unique=False)
    op.drop_column('location', 'type_')
    op.alter_column('favorites', 'location_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('favorites', 'characters_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
