"""empty message

Revision ID: f93fc32da02c
Revises: 15c1aac0edbe
Create Date: 2022-09-24 15:48:16.392808

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f93fc32da02c'
down_revision = '15c1aac0edbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('type_', sa.String(length=120), nullable=False))
    op.drop_index('type', table_name='characters')
    op.drop_index('type_2', table_name='characters')
    op.create_unique_constraint(None, 'characters', ['type_'])
    op.drop_column('characters', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('type', mysql.VARCHAR(length=120), nullable=False))
    op.drop_constraint(None, 'characters', type_='unique')
    op.create_index('type_2', 'characters', ['type'], unique=False)
    op.create_index('type', 'characters', ['type'], unique=False)
    op.drop_column('characters', 'type_')
    # ### end Alembic commands ###
